### ISSUE TITLE
Wrong BaseUrl generated by the Guidance when using 'Add Facade Rest Proxy' in the FrontEnd - Common project

### ISSUE THREAD

**Issue by SSantiagoDev** [GFlisch/Arc4u.Guidance.Doc#186]
**Description of the bug**
The BaseUrl generated by the Guidance is incorrect when using 'Add Facade Rest Proxy' in the FrontEnd - Common project

**To Reproduce**
1. Generate a Facade in the BackEnd
2. In the FrontEnd, right click on the Common project and then 'Add Facade Rest Proxy'
3. Select the Facade/SDK you've created
4. Open the generated *Facade.cs class, line 30
5. When using that BaseUrl we can see something like this (containing twice the name of the microservice):  https://localhost:7236/core/Core/facade/InstructionSet/Hello

**Expected behavior**
The BaseUrl should not contain twice the name of the microservice.
Should be like: `BaseUrl = $"{tokenSettings.Values["RootServiceUrl"].TrimEnd(new[] { '/' })}/"`

**Screenshots**
![image](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/2098804/5cbff692-a007-4e24-8197-4cccd7deb138)

**Desktop (please complete the following information):**
 - Visual Studio Version 17.2.5
 - Guidance Version 2022.2.1.12

**Comment by GFlisch** [comment]
Hi @SSantiagoDev,
Thanks for the issue found.
The cade has been reworked in the next version of the Guidance coming soon and the problem will be fixed.

The new version is working with settings registered and retrieve based on IOptionsMonitor<T>. The new code will be
        var tokenSettings = optionsSettings.Get("OAuth2");
        if (tokenSettings is not null)
        {
            var client = httpClientFactory.CreateClient("OAuth2");

            Proxy = new $(facadename)Client(client)
            {
                BaseUrl = tokenSettings.Values["RootServiceUrl"]
            };
        }
As you see the BaseUrl is not adding anymore the /core/ as mentioned in your example.
I have also removed the .TrimEnd because the proxy code generated does this for us:
var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/core/....");
