### ISSUE TITLE
Adapt program.cs of backends  to clearly separate the minimal code required for running nswag

### ISSUE THREAD

**Issue by ddewaleffe** [GFlisch/Arc4u.Guidance.Doc#218]
Idea would be to structure as: 

```cs
if (IsInvokedByNSwag) 
{ 
    // just the minimal code needed for NSwag to make its job.
}
else 
{
   // usual  code of program.cs 
}
```

Benefit would be that the nswag execution is not impacted by stuff we might add in program.cs
 That single if and would always work.

**Comment by rdarko** [comment]
We will take a look at the nswag inside of this task: [Consider Swashbuckle instead of NSwag: minimal API, kiota#69](https://github.com/GFlisch/Arc4u.Guidance.Doc/issues/69), and we will reevaluate how this affects the generation, so we wont be working on this task. Contact us privately if you disagree with this.
