### ISSUE TITLE
The reliance on https://guidancelic.arc4u.net/ is a usability risk

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#39]
Currently, the guidance can't operate without access to https://guidancelic.arc4u.net/.
In some environments (50Hz), access to https://guidancelic.arc4u.net/ is blocked. This can be tested by surfing to https://guidancelic.arc4u.net/swagger/interface: normally, you should see a login prompt in the browser:
In 50Hz, you'll see certificate failures.

Without access to this endpoint, the guidance is unusable.

**Comment by GFlisch** [comment]
The issue is identified. 50Hzt is using infoblox (a web proxy) to filter all http trafic (https or not). Theoretically they should use Palo Alto and use the same rule as at Elia. This alignment is not yet done and so we have to request to open the traffic to guidancelic.arc4u.net. This is why only 50Hzt is impacted.
We will discuss to open this.

**Comment by GFlisch** [comment]
Issue is fixed at the infra level
